CSV_DATA = {
  "dsa in cpp": [
    { "rank": 1, "channel_name": "CodeHelp - by Babbar", "playlist_title": "Complete C++ Placement DSA Course", "language": "Hindi/English", "level": "Beginner to Advanced", "video_count": 150, "duration_hours": 100, "description": "Highly structured learning with detailed notes and practice problems focused on placements.", "channel_url": "https://www.youtube.com/@CodeHelp", "playlist_url": "https://www.youtube.com/playlist?list=PLDzeHZWIZsTryvtXdMr6rPh4IDexB5NIA" },
    { "rank": 2, "channel_name": "take U forward (Striver)", "playlist_title": "Strivers A2Z-DSA Course", "language": "English", "level": "Beginner to Advanced", "video_count": 280, "duration_hours": 150, "description": "Deep technical logic and interview preparation for top-tier product-based companies.", "channel_url": "https://www.youtube.com/@takeUforward", "playlist_url": "https://www.youtube.com/playlist?list=PLgUwDviBIf0oF6QL8m22w1hIDC1vJ_BHz" },
    { "rank": 3, "channel_name": "Apna College", "playlist_title": "Complete C++ DSA Course", "language": "Hindi/English", "level": "Beginner", "video_count": 100, "duration_hours": 80, "description": "Visual learners who want clear concise explanations and placement focus.", "channel_url": "https://www.youtube.com/@ApnaCollegeOfficial", "playlist_url": "https://www.youtube.com/playlist?list=PLfqMhTWNBTe137I_EPQd34TsgV6IO55pt" },
    { "rank": 4, "channel_name": "Luv", "playlist_title": "Competitive Programming/DSA Course", "language": "Hindi/English", "level": "Intermediate to Advanced", "video_count": 120, "duration_hours": 70, "description": "Ideal for moving into Competitive Programming (CP) and mastering C++ STL.", "channel_url": "https://www.youtube.com/@LuvIsMe", "playlist_url": "https://www.youtube.com/playlist?list=PLauivoElc3ggagradg8MfOZreCMmXMmJ-" },
    { "rank": 5, "channel_name": "Aditya Verma", "playlist_title": "Dynamic Programming Playlist", "language": "Hindi", "level": "Intermediate", "video_count": 50, "duration_hours": 30, "description": "Mastering tough algorithmic topics like Dynamic Programming, Recursion, and Sliding Window.", "channel_url": "https://www.youtube.com/@AdityaVerma", "playlist_url": "https://www.youtube.com/playlist?list=PL_z_8CaSLPWekqhdCPmFohncHwz8TY2Go" },
    { "rank": 6, "channel_name": "College Wallah", "playlist_title": "C++ and DSA Foundation Course", "language": "Hindi", "level": "Beginner", "video_count": 140, "duration_hours": 90, "description": "Designed for students starting from the absolute basics of C++ programming.", "channel_url": "https://www.youtube.com/@CollegeWallahbyPW", "playlist_url": "https://www.youtube.com/playlist?list=PLxgZQoSe9cg0df_GxVjz3DD_Gck5tMXAd" },
    { "rank": 7, "channel_name": "CodeWithHarry", "playlist_title": "Data Structures and Algorithms Course in Hindi", "language": "Hindi", "level": "Beginner", "video_count": 95, "duration_hours": 70, "description": "Comprehensive coverage with easy-to-understand teaching style for logic building.", "channel_url": "https://www.youtube.com/@CodeWithHarry", "playlist_url": "https://www.youtube.com/playlist?list=PLu0W_9lII9ahIappRPN0MCAgtOu3lQjQi" },
    { "rank": 8, "channel_name": "Saurabh Shukla", "playlist_title": "Data Structure by Saurabh Shukla Sir", "language": "Hindi", "level": "Beginner", "video_count": 80, "duration_hours": 60, "description": "Great for building a strong foundation in core Data Structure logic and academics.", "channel_url": "https://www.youtube.com/@MySirG", "playlist_url": "https://www.youtube.com/playlist?list=PLsFNQxKNzefJNztGGoQC-59UhSwIaiIW3" },
    { "rank": 9, "channel_name": "GeeksforGeeks", "playlist_title": "DSA Self Paced Course Preview", "language": "English", "level": "Beginner to Advanced", "video_count": 110, "duration_hours": 80, "description": "Topic-specific deep dives and academic clarity with extensive problem-solving.", "channel_url": "https://www.youtube.com/@GeeksforGeeksVideos", "playlist_url": "https://www.youtube.com/playlist?list=PLqM7alHXFySFKsh8bHCBBFQR8ECBPS8GV" },
    { "rank": 10, "channel_name": "Abdul Bari", "playlist_title": "Algorithms", "language": "English", "level": "Intermediate", "video_count": 85, "duration_hours": 60, "description": "Understanding the complex mathematical and theoretical side of algorithms.", "channel_url": "https://www.youtube.com/@AbdulBariCode", "playlist_url": "https://www.youtube.com/playlist?list=PLDN4rrl48XKpZkf03iYFl-O29szjTrs_O" },
  ],
  "dsa in java": [
    { "rank": 1, "channel_name": "Kunal Kushwaha", "playlist_title": "Java + DSA Bootcamp", "language": "English", "level": "Beginner to Advanced", "video_count": 65, "duration_hours": 40, "description": "The ultimate deep dive into DSA using Java. Extremely detailed and perfect for absolute beginners to advanced levels with assignments.", "channel_url": "https://www.youtube.com/@KunalKushwaha", "playlist_url": "https://www.youtube.com/playlist?list=PL9gnSGHSqcnr_DxHsP7AW9ftq0AtAyYqJ" },
    { "rank": 2, "channel_name": "Pepcoding", "playlist_title": "DSA in Java (Level 1 & 2)", "language": "Hindi", "level": "Intermediate to Advanced", "video_count": 500, "duration_hours": 50, "description": "Problem-solving mastery focused heavily on pattern recognition and solving hundreds of questions.", "channel_url": "https://www.youtube.com/@Pepcoding", "playlist_url": "https://www.youtube.com/playlist?list=PL-Jc9J83PIiFj7YSPl2ulcpwy-mwj1SSk" },
    { "rank": 3, "channel_name": "Apna College", "playlist_title": "Java + DSA Series", "language": "Hindi", "level": "Beginner to Intermediate", "video_count": 80, "duration_hours": 35, "description": "Placement-ready highly structured DSA course in Java beginner-friendly and focused on product-based company interviews.", "channel_url": "https://www.youtube.com/@ApnaCollegeOfficial", "playlist_url": "https://www.youtube.com/playlist?list=PLfqMhTWNBTe137I_EPQd34TsgV6IO55pt" },
    { "rank": 4, "channel_name": "Anuj Bhaiya", "playlist_title": "DSA in Java", "language": "Hindi", "level": "Beginner to Intermediate", "video_count": 60, "duration_hours": 25, "description": "Clear and concise DSA course in Java with excellent whiteboard explanations before jumping into code.", "channel_url": "https://www.youtube.com/@AnujBhaiya", "playlist_url": "https://www.youtube.com/playlist?list=PLUcsbZa0qzu3yNzzAxgvSgRobdUUJvz7p" },
    { "rank": 5, "channel_name": "Telusko", "playlist_title": "Data Structures and Algorithms in Java", "language": "English", "level": "Beginner", "video_count": 40, "duration_hours": 15, "description": "Simple and easy DSA course in Java at a slower pace. Great for making sure core theory is solid.", "channel_url": "https://www.youtube.com/@Telusko", "playlist_url": "https://www.youtube.com/playlist?list=PLsyeobzWxl7oRKwDi7wjrANsbhTX0IK0J" },
    { "rank": 6, "channel_name": "CodeHelp - by Babbar", "playlist_title": "DSA Supreme (Java)", "language": "Hindi", "level": "Beginner to Intermediate", "video_count": 90, "duration_hours": 45, "description": "Comprehensive DSA course in Java by Love Babbar covering all major topics with a focus on placement preparation.", "channel_url": "https://www.youtube.com/@CodeHelp", "playlist_url": "https://www.youtube.com/playlist?list=PLDzeHZWIZsTqNW1gvXXAicBgku9uPZeOC" },
    { "rank": 7, "channel_name": "College Wallah", "playlist_title": "DSA in Java", "language": "Hindi", "level": "Beginner to Intermediate", "video_count": 70, "duration_hours": 30, "description": "Structured DSA in Java series for engineering students covering all core topics with academic focus.", "channel_url": "https://www.youtube.com/@CollegeWallahbyPW", "playlist_url": "https://www.youtube.com/playlist?list=PLxgZQoSe9cg2uGKIRzUbWaHRjEuZnAnhj" },
    { "rank": 8, "channel_name": "GeeksforGeeks", "playlist_title": "Data Structures and Algorithms", "language": "English", "level": "Beginner to Advanced", "video_count": 55, "duration_hours": 25, "description": "Official GeeksforGeeks DSA playlist covering all major data structures with clear explanations.", "channel_url": "https://www.youtube.com/@GeeksforGeeksVideos", "playlist_url": "https://www.youtube.com/playlist?list=PLqM7alHXFySGwOTADxwHrgH8m_XpgrB-k" },
    { "rank": 9, "channel_name": "Abdul Bari", "playlist_title": "Algorithms", "language": "English", "level": "Intermediate to Advanced", "video_count": 45, "duration_hours": 20, "description": "World-renowned algorithm series with deep theoretical explanations of sorting, searching, and graph algorithms.", "channel_url": "https://www.youtube.com/@AbdulBariCode", "playlist_url": "https://www.youtube.com/playlist?list=PLDN4rrl48XKpZkf03iYFl-O29szjTrs_O" },
    { "rank": 10, "channel_name": "Dinesh Varyani", "playlist_title": "Data Structures and Algorithms in Java", "language": "English", "level": "Beginner to Intermediate", "video_count": 40, "duration_hours": 18, "description": "Practical DSA course implemented in Java covering linked lists stacks queues trees graphs.", "channel_url": "https://www.youtube.com/@DineshVaryani", "playlist_url": "https://www.youtube.com/playlist?list=PL6Zs6LgrJj3tDXv8a_elC6eT_4R5gfX4d" },
  ],
  "dsa in python": [
    { "rank": 1, "channel_name": "Codebasics", "playlist_title": "Data Structures And Algorithms In Python", "language": "English", "level": "Beginner to Intermediate", "video_count": 35, "duration_hours": 15, "description": "Practical implementations of data structures with exercises and industry examples.", "channel_url": "https://www.youtube.com/@codebasics", "playlist_url": "https://www.youtube.com/playlist?list=PLeo1K3hjS3uu_n_a__MI_KktGTLYopZ12" },
    { "rank": 2, "channel_name": "Amulya's Academy", "playlist_title": "Data Structures | Python", "language": "English", "level": "Beginner", "video_count": 30, "duration_hours": 10, "description": "Clear and concise explanations of fundamental Python data structures.", "channel_url": "https://www.youtube.com/@AmulyasAcademy", "playlist_url": "https://www.youtube.com/playlist?list=PLzgPDYo_3xukPJdH6hVQ6Iic7KiJuoA-l" },
    { "rank": 3, "channel_name": "Jenny's Lectures CS IT", "playlist_title": "Data Structures and Algorithms", "language": "Hindi", "level": "Beginner", "video_count": 120, "duration_hours": 50, "description": "Focuses heavily on algorithm logic and whiteboard explanations applicable to Python.", "channel_url": "https://www.youtube.com/@jennyslecturescsit", "playlist_url": "https://www.youtube.com/playlist?list=PLdo5W4Nhv31bbKJzrsKfMpo_grxuLl8LU" },
    { "rank": 4, "channel_name": "Code and Debug", "playlist_title": "Data Structures and Algorithms with Python", "language": "Hindi", "level": "Beginner to Intermediate", "video_count": 45, "duration_hours": 20, "description": "Comprehensive playlist designed to help with interview prep and Python DSA.", "channel_url": "https://www.youtube.com/@CodeandDebug", "playlist_url": "https://www.youtube.com/playlist?list=PLhR2IpV1b2FwWwviBHRrR118YAaSlyhTU" },
    { "rank": 5, "channel_name": "Telusko", "playlist_title": "Data Structures and Algorithm", "language": "English", "level": "Beginner", "video_count": 25, "duration_hours": 10, "description": "Easy-to-understand basics of algorithms and data structures.", "channel_url": "https://www.youtube.com/@Telusko", "playlist_url": "https://www.youtube.com/playlist?list=PLsyeobzWxl7rF6HYJBTNuXy3CNxDkDl3V" },
    { "rank": 6, "channel_name": "freeCodeCamp.org", "playlist_title": "Algorithms and Data Structures Full Course", "language": "English", "level": "Beginner to Intermediate", "video_count": 1, "duration_hours": 10, "description": "A single 10-hour masterclass video covering DSA extensively in Python.", "channel_url": "https://www.youtube.com/@freecodecamp", "playlist_url": "https://www.youtube.com/watch?v=8hly31xKli0" },
    { "rank": 7, "channel_name": "GeeksforGeeks", "playlist_title": "Complete DSA Course | Data Structures and Algorithms", "language": "English", "level": "Intermediate", "video_count": 90, "duration_hours": 40, "description": "Problem-solving techniques for coding interviews and practical applications.", "channel_url": "https://www.youtube.com/@GeeksforGeeksVideos", "playlist_url": "https://www.youtube.com/playlist?list=PLqM7alHXFySF7JxK9E24C-ZeNAXFB1u8k" },
    { "rank": 8, "channel_name": "CodeWithHarry", "playlist_title": "Python for Beginners (Full Course)", "language": "Hindi", "level": "Beginner", "video_count": 100, "duration_hours": 30, "description": "Python basics transitioning into advanced logic and data structure concepts.", "channel_url": "https://www.youtube.com/@CodeWithHarry", "playlist_url": "https://www.youtube.com/playlist?list=PLu0W_9lII9agwh1XjRt242xIpHhPT2llg" },
    { "rank": 9, "channel_name": "NeetCode", "playlist_title": "Leetcode BLIND-75 Solutions", "language": "English", "level": "Intermediate to Advanced", "video_count": 75, "duration_hours": 25, "description": "Detailed video solutions for the famous Blind 75 LeetCode problem set in Python.", "channel_url": "https://www.youtube.com/@NeetCode", "playlist_url": "https://www.youtube.com/playlist?list=PLot-Xpze53ldVwtstag2TL4HQhAnC8ATf" },
    { "rank": 10, "channel_name": "Kunal Kushwaha", "playlist_title": "Complete Tree Data Structure Course", "language": "English", "level": "Intermediate to Advanced", "video_count": 25, "duration_hours": 10, "description": "Deep dive into Tree data structures, theory, and interview problems.", "channel_url": "https://www.youtube.com/@KunalKushwaha", "playlist_url": "https://www.youtube.com/playlist?list=PL9gnSGHSqcnqfctdbCQKaw5oZ9Up2cmsq" },
  ],
  "c data structures": [
    { "rank": 1, "channel_name": "Jenny's Lectures CS/IT", "playlist_title": "Data Structures and Algorithms", "language": "Hindi", "level": "Beginner to Intermediate", "video_count": 110, "duration_hours": 40, "description": "Best for university exams with 13+ years teaching experience covering DSA DAA DBMS and OS.", "channel_url": "https://www.youtube.com/@jennyslecturescsit", "playlist_url": "https://www.youtube.com/playlist?list=PLdo5W4NhNlICJ_feSAt036f0oatqH066z" },
    { "rank": 2, "channel_name": "Neso Academy", "playlist_title": "Data Structures using C", "language": "English", "level": "Beginner to Intermediate", "video_count": 60, "duration_hours": 25, "description": "Highly structured theory-based DSA course aligned with university and GATE exam syllabus.", "channel_url": "https://www.youtube.com/@nesoacademy", "playlist_url": "https://www.youtube.com/playlist?list=PLBlnK6fEyqRhX6r2uhhlubuF5yEXTdBRM" },
    { "rank": 3, "channel_name": "MyCodeSchool", "playlist_title": "Data Structures", "language": "English", "level": "Beginner to Intermediate", "video_count": 50, "duration_hours": 8, "description": "Best for mastering pointers linked lists trees and sorting using C and C++ with clear PPT-based explanations.", "channel_url": "https://www.youtube.com/@mycodeschool", "playlist_url": "https://www.youtube.com/playlist?list=PL2_aWCzGMAwLZp6LMUKI3cc7pgGsasm2_" },
    { "rank": 4, "channel_name": "CodeWithHarry", "playlist_title": "Data Structures and Algorithms in Hindi", "language": "Hindi", "level": "Beginner", "video_count": 40, "duration_hours": 15, "description": "Popular for placement preparation covering DSA concepts in Hindi with beginner-friendly explanations.", "channel_url": "https://www.youtube.com/@CodeWithHarry", "playlist_url": "https://www.youtube.com/playlist?list=PLu0W_9lII9aiXlHcLx-mDH1Qul38wD3a_" },
    { "rank": 5, "channel_name": "Gate Smashers", "playlist_title": "Data Structures (C/C++)", "language": "Hindi", "level": "Beginner to Intermediate", "video_count": 45, "duration_hours": 18, "description": "Focused on competitive exam and interview questions covering all major data structure topics.", "channel_url": "https://www.youtube.com/@GateSmashers", "playlist_url": "https://www.youtube.com/playlist?list=PLxCzCOWd7aiHCt7KDeif7I-W_T7L9Zz_w" },
    { "rank": 6, "channel_name": "Apna College", "playlist_title": "Data Structures and Algorithms", "language": "Hindi", "level": "Beginner", "video_count": 50, "duration_hours": 20, "description": "Fast-paced review course ideal for quick DSA revision and placement preparation.", "channel_url": "https://www.youtube.com/@ApnaCollegeOfficial", "playlist_url": "https://www.youtube.com/playlist?list=PLfqMhTWNBTe0b2nM6JHVCnEqst08ASbwW7" },
    { "rank": 7, "channel_name": "freeCodeCamp.org", "playlist_title": "C Programming and Data Structures (Full Course)", "language": "English", "level": "Beginner", "video_count": 1, "duration_hours": 8, "description": "Full course covering C programming fundamentals alongside core data structures.", "channel_url": "https://www.youtube.com/@freecodecamp", "playlist_url": "https://www.youtube.com/watch?v=KJgsSFOSQv0" },
    { "rank": 8, "channel_name": "Bro Code", "playlist_title": "C Programming Tutorial for Beginners", "language": "English", "level": "Beginner", "video_count": 35, "duration_hours": 10, "description": "Quick and concise C basics course covering syntax control flow functions arrays and pointers.", "channel_url": "https://www.youtube.com/@BroCodez", "playlist_url": "https://www.youtube.com/playlist?list=PLZPZq0r_RZOM6skzLqOm8VUMfgv_BW3mN" },
    { "rank": 9, "channel_name": "Jacob Sorber", "playlist_title": "C Programming (Memory and Linux Focus)", "language": "English", "level": "Intermediate to Advanced", "video_count": 40, "duration_hours": 12, "description": "Deep dive into memory management low-level Linux system programming and practical C concepts.", "channel_url": "https://www.youtube.com/@JacobSorber", "playlist_url": "https://www.youtube.com/playlist?list=PL9IEJIKnBJjH7m8eS986rDqP-Dsr-q853" },
    { "rank": 10, "channel_name": "ProgrammingKnowledge", "playlist_title": "C Programming for Absolute Beginners", "language": "English", "level": "Beginner", "video_count": 45, "duration_hours": 14, "description": "Ideal for absolute beginners covering ANSI GNU and K/R C standards with simple examples.", "channel_url": "https://www.youtube.com/@ProgrammingKnowledge", "playlist_url": "https://www.youtube.com/playlist?list=PLTXMOn73OnNSu_M0ZpU6uS_X5v0t6fMEn" },
  ],
  "cpp tutorials": [
    { "rank": 1, "channel_name": "The Cherno", "playlist_title": "C++", "language": "English", "level": "Beginner to Advanced", "video_count": 100, "duration_hours": 30, "description": "The go-to YouTube C++ playlist with ~12M views covering variables to memory management OOP modern C++ and design patterns.", "channel_url": "https://www.youtube.com/@TheCherno", "playlist_url": "https://www.youtube.com/playlist?list=PLlrATfBNZ98dudnM48yfGUldqGD0S4FFb" },
    { "rank": 2, "channel_name": "freeCodeCamp.org", "playlist_title": "C / C++", "language": "English", "level": "Beginner to Advanced", "video_count": 2, "duration_hours": 31, "description": "Comprehensive 31-hour C++ course covering fundamentals to advanced topics including OOP STL and memory management.", "channel_url": "https://www.youtube.com/@freecodecamp", "playlist_url": "https://www.youtube.com/playlist?list=PLWKjhJtqVAbmUE5IqyfGYEYjrZBYzaT4m" },
    { "rank": 3, "channel_name": "Bro Code", "playlist_title": "C++ Tutorial for Beginners", "language": "English", "level": "Beginner", "video_count": 45, "duration_hours": 10, "description": "Massive beginner-friendly C++ course covering syntax data structures OOP and practical coding exercises.", "channel_url": "https://www.youtube.com/@BroCodez", "playlist_url": "https://www.youtube.com/playlist?list=PLZPZq0r_RZOMHoXIcxze_lP97j2Ase2on" },
    { "rank": 4, "channel_name": "Caleb Curry", "playlist_title": "C++ Intermediate Tutorials", "language": "English", "level": "Intermediate", "video_count": 30, "duration_hours": 6, "description": "Deep dives into references pointers memory management and advanced C++ concepts for intermediate programmers.", "channel_url": "https://www.youtube.com/@CalebCurry", "playlist_url": "https://www.youtube.com/playlist?list=PL_c9BZzLwBRJkVDaJbLHrrjNH_phcbCy7" },
    { "rank": 5, "channel_name": "Programming with Mosh", "playlist_title": "C++ Tutorial for Beginners (Full Course)", "language": "English", "level": "Beginner", "video_count": 1, "duration_hours": 4, "description": "Clear concise course covering core C++ essentials with professional teaching quality.", "channel_url": "https://www.youtube.com/@programmingwithmosh", "playlist_url": "https://www.youtube.com/watch?v=ZzaPdXTrSb8" },
    { "rank": 6, "channel_name": "Neso Academy", "playlist_title": "C++ Programming", "language": "English", "level": "Beginner to Intermediate", "video_count": 55, "duration_hours": 20, "description": "Structured curriculum-aligned C++ course ideal for engineering students and GATE exam preparation.", "channel_url": "https://www.youtube.com/@nesoacademy", "playlist_url": "https://www.youtube.com/playlist?list=PLBlnK6fEyqRh6isJ01MBnbNpV3ZsktSyS" },
    { "rank": 7, "channel_name": "Gate Smashers", "playlist_title": "C++ Programming (Complete Course)", "language": "Hindi", "level": "Beginner to Intermediate", "video_count": 40, "duration_hours": 15, "description": "Complete C++ programming course tailored for computer science students and competitive exam aspirants.", "channel_url": "https://www.youtube.com/@GateSmashers", "playlist_url": "https://www.youtube.com/playlist?list=PLxCzCOWd7aiH6yRNI5OHQsnUJQfl7Geqj" },
    { "rank": 8, "channel_name": "CodeBeauty", "playlist_title": "C++ Programming (Full Course)", "language": "English", "level": "Beginner to Advanced", "video_count": 1, "duration_hours": 10, "description": "10-hour single-video full C++ course from beginner to advanced covering OOP pointers and dynamic memory.", "channel_url": "https://www.youtube.com/@CodeBeauty", "playlist_url": "https://www.youtube.com/watch?v=GQp1zzTwrRo" },
    { "rank": 9, "channel_name": "The Cherno", "playlist_title": "OpenGL (C++)", "language": "English", "level": "Advanced", "video_count": 45, "duration_hours": 12, "description": "Hands-on OpenGL graphics programming series using C++ covering shaders buffers textures and modern GPU techniques.", "channel_url": "https://www.youtube.com/@TheCherno", "playlist_url": "https://www.youtube.com/playlist?list=PLlrATfBNZ98foTJPJ_Ev03o2oq3-GGOS2" },
    { "rank": 10, "channel_name": "Caleb Curry", "playlist_title": "Data Structures and Algorithms (C++)", "language": "English", "level": "Intermediate", "video_count": 25, "duration_hours": 4, "description": "Focused DSA series in C++ covering big O notation searching sorting trees graphs.", "channel_url": "https://www.youtube.com/@CalebCurry", "playlist_url": "https://www.youtube.com/playlist?list=PL_c9BZzLwBRLpDEpYRFXKBN-2ZCsAx0ps" },
  ],
  "java tutorials": [
    { "rank": 1, "channel_name": "Bro Code", "playlist_title": "Java Tutorial for Beginners", "language": "English", "level": "Beginner", "video_count": 90, "duration_hours": 12, "description": "A comprehensive step-by-step guide covering the fundamentals of Java syntax OOP and more.", "channel_url": "https://www.youtube.com/@BroCodez", "playlist_url": "https://www.youtube.com/playlist?list=PLZPZq0r_RZOOj_NOZYq_R2PECIMglLemc" },
    { "rank": 2, "channel_name": "Telusko", "playlist_title": "Java Tutorial For Beginners", "language": "English", "level": "Beginner", "video_count": 85, "duration_hours": 12, "description": "Excellent for conceptual understanding especially for those looking to understand the why behind the code.", "channel_url": "https://www.youtube.com/@Telusko", "playlist_url": "https://www.youtube.com/playlist?list=PLsyeobzWxl7pe_IiTfNyr55kwJPWbgxB5" },
    { "rank": 3, "channel_name": "Coding with John", "playlist_title": "Java Beginner", "language": "English", "level": "Beginner", "video_count": 40, "duration_hours": 10, "description": "Focuses on explaining difficult Java concepts like Lambda expressions and Multithreading in a very simple direct manner.", "channel_url": "https://www.youtube.com/@CodingWithJohn", "playlist_url": "http://www.youtube.com/playlist?list=PLkeaG1zpPTHiMjczpmZ6ALd46VjjiQJ_8" },
    { "rank": 4, "channel_name": "Programming with Mosh", "playlist_title": "Java Tutorials", "language": "English", "level": "Beginner", "video_count": 1, "duration_hours": 2.5, "description": "Known for clear concise explanations of core Java concepts and professional coding practices.", "channel_url": "https://www.youtube.com/@programmingwithmosh", "playlist_url": "https://www.youtube.com/playlist?list=PLTjRvDozrdlyjm_nKyYt4b5C1zx4Xdaut" },
    { "rank": 5, "channel_name": "freeCodeCamp.org", "playlist_title": "Java Tutorials", "language": "English", "level": "Beginner to Advanced", "video_count": 30, "duration_hours": 30, "description": "A variety of long-form tutorials and structured lessons for beginners to advanced learners.", "channel_url": "https://www.youtube.com/@freecodecamp", "playlist_url": "https://www.youtube.com/playlist?list=PLWKjhJtqVAbnRT_hue-3zyiuIYj0OlpyG" },
    { "rank": 6, "channel_name": "Amigoscode", "playlist_title": "Java Tutorial - Learn Java", "language": "English", "level": "Beginner to Intermediate", "video_count": 45, "duration_hours": 3, "description": "Focuses on modern Java development with a clean and clear teaching style.", "channel_url": "https://www.youtube.com/@Amigoscode", "playlist_url": "https://www.youtube.com/playlist?list=PLwvrYc43l1MyAmDss3HEYYBIQwY3pITeA" },
    { "rank": 7, "channel_name": "Java Brains", "playlist_title": "Java & Spring Boot", "language": "English", "level": "Intermediate to Advanced", "video_count": 60, "duration_hours": 8, "description": "Highly regarded for technical depth in core Java and enterprise technologies.", "channel_url": "https://www.youtube.com/@JavaBrains", "playlist_url": "https://www.youtube.com/playlist?list=PLqq-6Pq4lTTbx8p2oCgcAQGQyqN8XeA1x" },
    { "rank": 8, "channel_name": "Alex Lee", "playlist_title": "Full Java Course", "language": "English", "level": "Beginner", "video_count": 50, "duration_hours": 6, "description": "Fast-paced and engaging tutorials that help you get up and running with Java quickly.", "channel_url": "https://www.youtube.com/@AlexLee", "playlist_url": "https://www.youtube.com/playlist?list=PL59LTecnGM1NRUyune3SxzZlYpZezK-oQ" },
    { "rank": 9, "channel_name": "Caleb Curry", "playlist_title": "Java Programming Tutorials", "language": "English", "level": "Beginner to Intermediate", "video_count": 40, "duration_hours": 7, "description": "A detailed breakdown of programming logic and Java-specific syntax.", "channel_url": "https://www.youtube.com/@CalebCurry", "playlist_url": "https://www.youtube.com/playlist?list=PL_c9BZzLwBRJ55lLw8PdPlTVblIlPKfX5" },
    { "rank": 10, "channel_name": "Edureka", "playlist_title": "Java Full Course", "language": "English", "level": "Beginner to Advanced", "video_count": 1, "duration_hours": 12, "description": "A marathon session covering everything from basic setup to advanced Java topics in a single extensive video.", "channel_url": "https://www.youtube.com/@edureka", "playlist_url": "https://www.youtube.com/watch?v=TTWjbg_go3A" },
  ],
  "python tutorials": [
    { "rank": 1, "channel_name": "Corey Schafer", "playlist_title": "Python OOP Tutorials - Working with Classes", "language": "English", "level": "Intermediate", "video_count": 6, "duration_hours": 2, "description": "Focuses on Object-Oriented Programming principles including classes inheritance and special methods.", "channel_url": "https://www.youtube.com/@coreyms", "playlist_url": "https://www.youtube.com/playlist?list=PL-osiE80TeTsqhIuOqKhwlXsIBIdSeYtc" },
    { "rank": 2, "channel_name": "Tech With Tim", "playlist_title": "Expert Python Tutorials", "language": "English", "level": "Advanced", "video_count": 10, "duration_hours": 2, "description": "Advanced topics such as decorators generators and dunder methods for experienced developers.", "channel_url": "https://www.youtube.com/@TechWithTim", "playlist_url": "https://www.youtube.com/playlist?list=PLzMcBGfZo4-kwmIcMDdXSuy_wSqtU-xDP" },
    { "rank": 3, "channel_name": "Sentdex", "playlist_title": "Machine Learning with Python", "language": "English", "level": "Intermediate to Advanced", "video_count": 60, "duration_hours": 10, "description": "Deep dives into the math and application of machine learning algorithms from scratch.", "channel_url": "https://www.youtube.com/@sentdex", "playlist_url": "https://www.youtube.com/playlist?list=PLQVvvaa0QuDfKTOs3Keq_kaG2P55YRn5v" },
    { "rank": 4, "channel_name": "freeCodeCamp.org", "playlist_title": "Data Analysis with Python Course", "language": "English", "level": "Beginner to Intermediate", "video_count": 40, "duration_hours": 19, "description": "Comprehensive training on using libraries like Numpy Pandas and Matplotlib.", "channel_url": "https://www.youtube.com/@freecodecamp", "playlist_url": "https://www.youtube.com/playlist?list=PLWKjhJtqVAblvI1i46ScbKV2jH1gdL7VQ" },
    { "rank": 5, "channel_name": "Tech With Tim", "playlist_title": "Python Machine Learning Tutorials", "language": "English", "level": "Intermediate", "video_count": 30, "duration_hours": 5, "description": "Practical implementation of machine learning using Scikit-learn and other popular libraries.", "channel_url": "https://www.youtube.com/@TechWithTim", "playlist_url": "https://www.youtube.com/playlist?list=PLzMcBGfZo4-mP7qA9cagf68V06sko5otr" },
    { "rank": 6, "channel_name": "Sentdex", "playlist_title": "Intermediate Python Programming", "language": "English", "level": "Intermediate", "video_count": 25, "duration_hours": 4, "description": "Bridge the gap between beginner and advanced Python with topics like multithreading and argument parsing.", "channel_url": "https://www.youtube.com/@sentdex", "playlist_url": "https://www.youtube.com/playlist?list=PLQVvvaa0QuDfju7ADVp5W1GF9jVhjbX-_" },
    { "rank": 7, "channel_name": "Corey Schafer", "playlist_title": "Python Tutorials", "language": "English", "level": "Beginner to Advanced", "video_count": 130, "duration_hours": 30, "description": "Widely considered one of the best general-purpose Python series for all skill levels.", "channel_url": "https://www.youtube.com/@coreyms", "playlist_url": "https://www.youtube.com/playlist?list=PL-osiE80TeTt2d9bfVyTiXJA-UTHn6WwU" },
    { "rank": 8, "channel_name": "Programming with Mosh", "playlist_title": "Python Tutorials", "language": "English", "level": "Beginner", "video_count": 1, "duration_hours": 6, "description": "Very clear high-quality production focusing on the core essentials for quick learning.", "channel_url": "https://www.youtube.com/@programmingwithmosh", "playlist_url": "https://www.youtube.com/playlist?list=PLTjRvDozrdlyj5wgH4qkvwSOdHLOCx10f" },
    { "rank": 9, "channel_name": "Bro Code", "playlist_title": "Python Tutorial for Beginners", "language": "English", "level": "Beginner", "video_count": 80, "duration_hours": 12, "description": "A massive all-in-one beginner course that covers syntax data structures and GUI development.", "channel_url": "https://www.youtube.com/@BroCodez", "playlist_url": "https://www.youtube.com/playlist?list=PLZPZq0r_RZOOkUQbat8LyQii36cJf2SWT" },
    { "rank": 10, "channel_name": "freeCodeCamp.org", "playlist_title": "Python Tutorials", "language": "English", "level": "Beginner to Advanced", "video_count": 50, "duration_hours": 40, "description": "A collection of various Python paths including beginner basics and scientific computing.", "channel_url": "https://www.youtube.com/@freecodecamp", "playlist_url": "https://www.youtube.com/playlist?list=PLWKjhJtqVAbnqBxcdjVGgT3uVR10bzTEB" },
  ],
}

SKILL_ALIASES = {
  "dsa cpp": "dsa in cpp", "dsa c++": "dsa in cpp", "c++ dsa": "dsa in cpp", "cpp dsa": "dsa in cpp",
  "dsa java": "dsa in java", "java dsa": "dsa in java",
  "dsa python": "dsa in python", "python dsa": "dsa in python",
  "c data structure": "c data structures", "data structures c": "c data structures",
  "c++": "cpp tutorials", "cpp": "cpp tutorials", "c plus plus": "cpp tutorials",
  "java": "java tutorials",
  "python": "python tutorials",
}

def get_duration_category(hours):
    if hours < 15: return "Short"
    if hours <= 40: return "Medium"
    return "Long"

def score_from_rank(rank):
    return max(60, 100 - (rank - 1) * 4)

def find_in_curated_data(skill):
    normalized = skill.lower().strip()
    if normalized in CSV_DATA: return CSV_DATA[normalized]
    if normalized in SKILL_ALIASES: return CSV_DATA[SKILL_ALIASES[normalized]]
    
    # Partial match
    for key in CSV_DATA:
        if key in normalized or normalized in key:
            return CSV_DATA[key]
    return None
